# SVM-(ver3)-newData Classifier

# -*- coding: utf-8 -*-
"""water quality SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19-cWsamC90rp5xmkM7x6URe4scJ-ZUeM
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics

# loading csv file
file_path = "waterQuality2.csv"
dataset=pd.read_csv(file_path)

# preprocessing
dataset = dataset[dataset['is_safe'] != '#NUM!']
dataset['is_safe'] = dataset['is_safe'].astype(float)
dataset = dataset[dataset['ammonia'] != '#NUM!']
dataset['ammonia'] = dataset['ammonia'].astype(float)

# loop on the data from to get the norm of the cols :
for i in dataset.columns:
    dataset[i] = (dataset[i]-dataset[i].min()) / (dataset[i].max()-dataset[i].min())

x = dataset.drop('is_safe', axis=1)   # to designate that you want to drop a column
y = dataset.is_safe

# splitting the data
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

clf = (svm.SVC(kernel='linear')).fit(X_train, y_train)

print("Accuracy:", metrics.accuracy_score(y_test, clf.predict(X_test)))
