# -*- coding: utf-8 -*-
"""XGBOOT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-n9EHMwQaxv7j_lQrOK-_wUznEbphWV1
"""

import csv
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
#loading csv file
file_path ='/content/water_potability.csv'
dataset=pd.read_csv(file_path)
dataset.head()

#preprocessing 

# normalization step :
def getTheNorm ( col):
    return ( ( col-col.min())/(col.max()-col.min()))
## loop on the data fram to get the norm of the cols :
for col in  dataset.columns :
    dataset[col]= getTheNorm(dataset[col])

dataset["ph"].fillna(value = dataset["ph"].mean(), inplace =True)
dataset["Hardness"].fillna(value = dataset["Hardness"].mean(), inplace =True)
dataset["Chloramines"].fillna(value = dataset["Chloramines"].mean(), inplace =True)
dataset["Conductivity"].fillna(value = dataset["Conductivity"].mean(), inplace =True)
dataset["Organic_carbon"].fillna(value = dataset["Organic_carbon"].mean(), inplace =True)
dataset["Turbidity"].fillna(value = dataset["Turbidity"].mean(), inplace =True)
dataset['Trihalomethanes'].fillna(value = dataset['Trihalomethanes'].mean(), inplace =True)
dataset["Sulfate"].fillna(value = dataset["Sulfate"].mean(), inplace =True)


# remove duplicates
dataset.drop_duplicates(keep='first',inplace=True)

#Model
X = dataset.drop('Potability',axis=1)
Y = dataset.Potability
x_scaled= preprocessing.scale(X)
#splitting the data
X_train, X_test, y_train, y_test = train_test_split(x_scaled, Y,test_size=0.22,shuffle=True,random_state=42)
           
from xgboost import XGBClassifier
xgb_clf=XGBClassifier()
xgb_clf.fit(X_train,y_train)
score=xgb_clf.score(X_test,y_test)
print(score)